def ListMethod():
    List = [8, 13, 27]
    print("List: ", List)
    List.append(1)
    print("After appending 1: ", List)
    List.extend([98, 99])
    print("After extending List: ", List)
    List.insert(1, 1)
    print("After inserting element at Index 1: ", List)
    List.sort()
    print("After Sorting: ", List)
    List.remove(99)
    print("After removing element 99: ", List)
    List.pop(3)
    print("After popping at Index 3", List)
    List.reverse()
    print("After reversing the list: ", List)
    cpy = List.copy()
    print("After copying List to cpy: ", cpy)
    cpy.clear()
    print("Clearing the list cpy", cpy)
ListMethod()